CREATE DATABASE IF NOT EXISTS mvc_quill DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS category (
  id INT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL UNIQUE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS question (
  id INT UNSIGNED AUTO_INCREMENT,
  category_id INT,
  text VARCHAR(2048) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS answer (
  id INT UNSIGNED AUTO_INCREMENT,
  question_id INT,
  text VARCHAR(2048) NOT NULL,
  is_correct BOOLEAN,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;